//! Configuration: zero-config defaults plus an optional TOML file.
//!
//! The watcher runs with no config file at all. If a file exists at
//! [`config_path`], its values override the defaults. A `config` subcommand
//! generates a starter file (see [`generate`]) so users don't have to hunt for
//! the platform-specific path.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Top-level configuration. Every field is optional in the TOML file thanks to
/// `#[serde(default)]`; missing keys fall back to [`Default`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// How often (seconds) to scan local processes for a running Steam game.
    pub poll_interval_seconds: u64,
    /// Disable local process scanning entirely (rely only on the optional Steam
    /// Web API layer). Lets privacy-conscious users opt out of process reads.
    pub disable_process_scan: bool,
    /// aw-server connection settings.
    pub server: ServerConfig,
    /// Optional Steam Web API layer. `None` (section absent) keeps the watcher
    /// fully local and offline.
    pub steam_api: Option<SteamApiConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ServerConfig {
    pub host: String,
    pub port: u16,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SteamApiConfig {
    /// Steam Web API key (https://steamcommunity.com/dev/apikey).
    pub api_key: String,
    /// Your 64-bit SteamID.
    pub steam_id: String,
    /// Poll interval for the API layer; kept slower to respect rate limits.
    #[serde(default = "default_api_poll")]
    pub poll_interval_seconds: u64,
    /// Whether to also report friends' currently-playing games.
    #[serde(default = "default_true")]
    pub track_friends: bool,
}

fn default_api_poll() -> u64 {
    60
}
fn default_true() -> bool {
    true
}

impl Default for Config {
    fn default() -> Self {
        Config {
            poll_interval_seconds: 15,
            disable_process_scan: false,
            server: ServerConfig::default(),
            steam_api: None,
        }
    }
}

impl Default for ServerConfig {
    fn default() -> Self {
        ServerConfig {
            host: "localhost".to_string(),
            port: 5600,
        }
    }
}

/// The path the config file is (or would be) read from:
/// `<config-dir>/activitywatch/aw-watcher-steam-rs/config.toml`.
pub fn config_path() -> Option<PathBuf> {
    directories::BaseDirs::new().map(|dirs| {
        dirs.config_dir()
            .join("activitywatch")
            .join("aw-watcher-steam-rs")
            .join("config.toml")
    })
}

/// Load config from [`config_path`], falling back to defaults if the file is
/// absent. A present-but-malformed file is a hard error so the user notices.
pub fn load() -> Result<Config, Box<dyn std::error::Error>> {
    let Some(path) = config_path() else {
        log::warn!("could not determine a config directory; using defaults");
        return Ok(Config::default());
    };
    match fs::read_to_string(&path) {
        Ok(contents) => {
            log::info!("loaded config from {}", path.display());
            Ok(toml::from_str(&contents)?)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            log::info!("no config file at {}; using defaults", path.display());
            Ok(Config::default())
        }
        Err(e) => Err(Box::new(e)),
    }
}

/// Commented-out example written by `config --generate`. Every line is a
/// comment so the generated file changes nothing until the user edits it.
const EXAMPLE_CONFIG: &str = r#"# Configuration for aw-watcher-steam-rs
# All settings are optional; uncomment a line to override the default shown.
# Generated by `aw-watcher-steam-rs config --generate`.

# How often (seconds) to scan local processes for a running Steam game.
# poll_interval_seconds = 15

# Set to true to disable local process scanning entirely and rely only on the
# Steam Web API layer below.
# disable_process_scan = false

# [server]
# host = "localhost"
# port = 5600

# --- Optional: Steam Web API layer (self + friends) ---
# Uncomment and fill in to also report what you and your friends are currently
# playing. Requires network access. Get a key at
# https://steamcommunity.com/dev/apikey
# [steam_api]
# api_key = "YOUR_STEAM_WEB_API_KEY"
# steam_id = "76561197960287930"
# poll_interval_seconds = 60
# track_friends = true
"#;

/// Write the commented example config to [`config_path`], creating parent
/// directories. Refuses to overwrite an existing file unless `force` is set.
/// Returns the path written so the caller can log it.
pub fn generate(force: bool) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = config_path().ok_or("could not determine a config directory")?;
    if path.exists() && !force {
        return Err(format!(
            "config already exists at {} (pass --force to overwrite)",
            path.display()
        )
        .into());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, EXAMPLE_CONFIG)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_zero_config() {
        let c = Config::default();
        assert_eq!(c.poll_interval_seconds, 15);
        assert_eq!(c.server.port, 5600);
        assert!(c.steam_api.is_none());
        assert!(!c.disable_process_scan);
    }

    #[test]
    fn empty_toml_yields_defaults() {
        let c: Config = toml::from_str("").unwrap();
        assert_eq!(c.server.host, "localhost");
        assert!(c.steam_api.is_none());
    }

    #[test]
    fn partial_toml_overrides_only_given_keys() {
        let c: Config =
            toml::from_str("poll_interval_seconds = 10\n[server]\nport = 1234").unwrap();
        assert_eq!(c.poll_interval_seconds, 10);
        assert_eq!(c.server.port, 1234);
        assert_eq!(c.server.host, "localhost"); // untouched default
    }

    #[test]
    fn steam_api_section_enables_layer2() {
        let toml = "[steam_api]\napi_key = \"k\"\nsteam_id = \"123\"";
        let c: Config = toml::from_str(toml).unwrap();
        let api = c.steam_api.expect("section present");
        assert_eq!(api.api_key, "k");
        assert_eq!(api.poll_interval_seconds, 60); // defaulted
        assert!(api.track_friends);
    }

    #[test]
    fn example_config_parses_as_empty() {
        // All lines are comments, so it must parse and equal the defaults.
        let c: Config = toml::from_str(EXAMPLE_CONFIG).unwrap();
        assert_eq!(c.poll_interval_seconds, 5);
        assert!(c.steam_api.is_none());
    }
}
